version: "3.8"

services:
  app:
    build: ./Backend
    container_name: urbango
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./Backend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    container_name: urbango_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: urban_user
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: urbango_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: horachioae@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  
  traccar:
    container_name: urbango_traccar
    image: traccar/traccar:latest
    restart: always
    depends_on:
      - db
    volumes:
      - ./traccar.xml:/opt/traccar/conf/traccar.xml
    ports:
      - "8082:8082" 
      - "5013:5013"

volumes:
  db_data: {}
  node_modules: {}
  pgadmin_data: {}